# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Image_Updater

on:
  schedule: 
    - cron: 5 * * * *
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install fonts-freefont-ttf
        python -m pip install --upgrade pip
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt
    - name: Run it
      run: |
        source env/bin/activate
        python main.py
    - name: Set current date as env variable
      run: echo "::set-env name=NOW::$(date)"
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Required
        commit_message: Workflow image update at ${{ env.NOW }}

        # Optional glob pattern of files which should be added to the commit
        # See the `pathspec`-documentation for git
        # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
        # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
        file_pattern: "*.png"



